[CmdletBinding()]
param(
  [string]$Baseline,
  [string]$ReadmePath = 'QuickClipsPersonalization/README.md'
)

$ErrorActionPreference = 'Stop'

$scriptDir = Split-Path -Parent $MyInvocation.MyCommand.Path
$repoRoot = Resolve-Path (Join-Path $scriptDir '..')
Set-Location $repoRoot

function Invoke-Git {
  param(
    [Parameter(Mandatory = $true)]
    [string[]]$Arguments
  )

  $output = & git @Arguments
  if ($LASTEXITCODE -ne 0) {
    throw "git $($Arguments -join ' ') failed."
  }
  return $output
}

if (-not $Baseline) {
  $baselineFile = Join-Path $scriptDir 'ui-baseline.txt'
  if (Test-Path $baselineFile) {
    $Baseline = Get-Content $baselineFile |
      Where-Object { $_ -and -not $_.TrimStart().StartsWith('#') } |
      Select-Object -First 1
  }
}

if (-not $Baseline) {
  throw 'No baseline commit provided. Pass -Baseline or set QuickClipsPersonalization/ui-baseline.txt.'
}

$Baseline = $Baseline.Trim()

$uiFiles = @(
  'assets/personalization-preview.css',
  'assets/personalization-preview.js',
  'snippets/personalization-preview-modal.liquid',
  'snippets/personalization-line-item-properties.liquid',
  'snippets/personalization-preview-trigger.liquid'
)

$baselineMetaLine = (Invoke-Git -Arguments @('show', '-s', '--date=short', '--format=%h|%ad|%s', $Baseline) | Select-Object -First 1)
if (-not $baselineMetaLine) {
  throw "Unable to read baseline commit metadata for '$Baseline'."
}
$baselineParts = $baselineMetaLine -split '\|', 3
$baselineHash = $baselineParts[0]
$baselineDate = $baselineParts[1]
$baselineSubject = $baselineParts[2]

$statusByFile = @{}
$statusLines = Invoke-Git -Arguments (@('diff', '--name-status', "$Baseline..HEAD", '--') + $uiFiles)
foreach ($line in $statusLines) {
  if (-not $line) { continue }
  $parts = $line -split "`t"
  if ($parts.Count -lt 2) { continue }

  $rawStatus = $parts[0]
  $status = $rawStatus.Substring(0, 1)
  $file = $parts[-1]
  $statusByFile[$file] = $status
}

$numstatByFile = @{}
$numstatLines = Invoke-Git -Arguments (@('diff', '--numstat', "$Baseline..HEAD", '--') + $uiFiles)
foreach ($line in $numstatLines) {
  if (-not $line) { continue }
  $parts = $line -split "`t", 3
  if ($parts.Count -ne 3) { continue }

  $added = if ($parts[0] -eq '-') { 0 } else { [int]$parts[0] }
  $deleted = if ($parts[1] -eq '-') { 0 } else { [int]$parts[1] }
  $file = $parts[2]
  $numstatByFile[$file] = @{
    Added = $added
    Deleted = $deleted
  }
}

function Get-StatusLabel {
  param([string]$StatusCode)
  switch ($StatusCode) {
    'A' { 'Added' }
    'M' { 'Modified' }
    'D' { 'Deleted' }
    'R' { 'Renamed' }
    'C' { 'Copied' }
    default { 'Unchanged' }
  }
}

$rows = New-Object System.Collections.Generic.List[string]
$changedCount = 0
$totalAdded = 0
$totalDeleted = 0
$code = [char]96

foreach ($file in $uiFiles) {
  $statusCode = if ($statusByFile.ContainsKey($file)) { $statusByFile[$file] } else { '=' }
  $statusLabel = Get-StatusLabel -StatusCode $statusCode

  $added = 0
  $deleted = 0
  if ($numstatByFile.ContainsKey($file)) {
    $added = [int]$numstatByFile[$file].Added
    $deleted = [int]$numstatByFile[$file].Deleted
  }

  if ($statusLabel -ne 'Unchanged') {
    $changedCount += 1
  }

  $totalAdded += $added
  $totalDeleted += $deleted

  $latestLine = (& git log "$Baseline..HEAD" --date=short '--pretty=format:%h|%ad|%s' -- $file | Select-Object -First 1)
  $latestText = if ($latestLine) {
    $latestParts = $latestLine -split '\|', 3
    "$code$($latestParts[0])$code ($($latestParts[1])) - $($latestParts[2])"
  } else {
    'No changes since baseline'
  }

  $rows.Add("| $code$file$code | $statusLabel | $added | $deleted | $latestText |")
}

$generatedAt = Get-Date -Format 'yyyy-MM-dd HH:mm:ss zzz'
$generatedBody = @"
### Auto-Generated UI Diff

Generated by $($code)QuickClipsPersonalization/update-ui-readme.ps1$($code) on $generatedAt.

Baseline commit: $code$baselineHash$code ($baselineDate) - $baselineSubject

Changed UI files: $changedCount/$($uiFiles.Count)  
Total line delta: +$totalAdded / -$totalDeleted

| File | Status | +Lines | -Lines | Latest change |
| --- | --- | ---: | ---: | --- |
$($rows -join "`n")
"@

$readmeFullPath = Join-Path $repoRoot $ReadmePath
if (-not (Test-Path $readmeFullPath)) {
  throw "README file not found at '$ReadmeFullPath'."
}

$startMarker = '<!-- UI_CHANGES_AUTOGEN:START -->'
$endMarker = '<!-- UI_CHANGES_AUTOGEN:END -->'

$content = Get-Content $readmeFullPath -Raw
if (-not $content.Contains($startMarker) -or -not $content.Contains($endMarker)) {
  throw "README must include markers: $startMarker and $endMarker."
}

$pattern = "(?s)$([regex]::Escape($startMarker)).*?$([regex]::Escape($endMarker))"
$replacement = "$startMarker`r`n`r`n$generatedBody`r`n`r`n$endMarker"
$updated = [regex]::Replace($content, $pattern, $replacement, 1)

$utf8NoBom = New-Object System.Text.UTF8Encoding($false)
[System.IO.File]::WriteAllText($readmeFullPath, $updated, $utf8NoBom)

Write-Output "Updated $ReadmePath using baseline $Baseline."
